### ISSUE TITLE
[BUG] @EffectAlgebra generates uncompilable *Ops when the type parameter is not named A

### ISSUE THREAD

**Issue by MagnusSmith** [higher-kinded-j/higher-kinded-j#699]
> **Naming note:** no new API names. This is about the generator reconciling two names it already uses.

**Describe the bug**

`@EffectAlgebra` validates that an algebra has exactly *one* type parameter, but the generated `*Ops` assumes that parameter is *named* `A`. Name it anything else and the generated code does not compile, with the error sited in a file the user never wrote.

`EffectAlgebraProcessor.generateOpsMethod` declares the generated method's own type variable as a hard-coded `A`:

```java
TypeVariableName typeA = TypeVariableName.get("A");   // EffectAlgebraProcessor.java:521
```

but copies each record component's type verbatim:

```java
builder.addParameter(TypeName.get(component.asType()), ...);   // :530
```

If the algebra declares `RenamedOp<T>`, the copied type still mentions `T`, which is not in scope in the generated static method.

**To Reproduce**

An algebra identical to a working one except the type parameter is named `T`:

```java
@EffectAlgebra
public sealed interface RenamedOp<T> permits RenamedOp.Only {
  <B> RenamedOp<B> mapK(Function<? super T, ? extends B> f);

  record Only<T>(String text, Function<Unit, T> k) implements RenamedOp<T> {
    @Override
    public <B> RenamedOp<B> mapK(Function<? super T, ? extends B> f) {
      return new Only<>(text, k.andThen(f));
    }
  }
}
```

```
RenamedOpOps.java:40: error: cannot find symbol
  symbol:   class T
  location: class RenamedOpOps
RenamedOpOps.java:79: error: cannot find symbol
  symbol:   class T
  location: class Bound<G>
2 errors
```

The generated method mixes the two names:

```java
public static <A> Free<RenamedOpKind.Witness, A> only(String text, Function<Unit, T> k) {
  RenamedOp<A> op = new RenamedOp.Only<>(text, k);
  ...
}
```

`<A>` is declared, `T` is used.

**Expected behaviour**

Either the algebra's type parameter name is irrelevant (preferred), or naming it something else is rejected at the declaration with a message that says so.

**Scope**

Only `*Ops` is affected — both the static factory and the nested `Bound`. The other four generated types are fine, because none of them copies a record component's type:

| generated | with `<T>` |
|---|---|
| `RenamedOpKind` | ✅ |
| `RenamedOpKindHelper` | ✅ |
| `RenamedOpFunctor` | ✅ |
| `RenamedOpInterpreter` | ✅ |
| `RenamedOpOps` | ❌ `cannot find symbol: class T` |

**Why it is easy to hit and hard to diagnose**

- `EffectAlgebraProcessor.java:94-100` validates the type-parameter **count**, not its name: `getTypeParameters().size() != 1`.
- The `@EffectAlgebra` javadoc calls it "exactly one type parameter (the result type `A`)" and every example uses `A` — so `A` reads as a description of the parameter's *role*, not a required spelling.
- Nothing fails at the user's declaration. The error appears in generated source, naming a symbol from a file they did not write.

**Suggested fix**

Substitute rather than restrict. `EffectAlgebraProcessor.java:104` already rejects permitted records that introduce type parameters beyond the algebra's, so each permitted record has exactly one type variable and it always corresponds to the generated `A`. Rewriting that variable to `A` while copying component types makes any name work:

```mermaid
flowchart LR
    D["algebra declares &lt;T&gt;"] --> C["component type<br/>Function&lt;Unit, T&gt;"]
    C -->|"copied verbatim (today)"| B["Function&lt;Unit, T&gt; in a method declaring &lt;A&gt;<br/>❌ cannot find symbol"]
    C -->|"rewrite sole type variable → A"| G["Function&lt;Unit, A&gt;<br/>✅"]
```

The cheaper floor, if substitution is not wanted: extend the existing count check to require the name, so the diagnostic lands on the algebra's declaration instead of on generated code.

**Environment**

- Reproduced on `main` at `557b14e35`, JDK 25, `hkj-processor` run directly via `javac -processorpath`.
- Pre-existing; not introduced by #695/#696/#698.

**Found via**

Surfaced by a review probe while working on #698 (`@ComposeEffects` typed support), which composes algebras and so exercises `*Ops`. Unrelated to that change.
